<a href="https://colab.research.google.com/github/ashishshaji/assignment_ineuron/blob/master/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Write a function so that the columns of the output matrix are powers of the input vector. 

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
# Inputing the vector from the user
import numpy as np
user_array=[]
n=int(input('enter no of elements:'))
for i in range(n):
    e=int(input( i))
    user_array.append(e)
    
# Converting list to numpy array    
user_array=np.array(user_array) 
print('input vector:',user_array)


enter no of elements:3
1
12
23
input vector: [1 2 3]


In [2]:
# Defining a function to find the Vandermonde matrix
def vander_mat(x,N):
    x=np.column_stack([x**(N-1-i) for i in range(N)])
    print(x)
      
vander_mat(user_array,n)

[[1 1 1]
 [4 2 1]
 [9 3 1]]


#### 2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
x=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
print('input array:',x)

def mov_avg(x,k):
    for i in range(len(x)-2):
        sum=0
        for j in range(i,i+k):
            sum+=x[j]
        print('y'+str(i),int(sum/k))
        
mov_avg(x,k)

input array: [  3   5   7   2   8  10  11  65  72  81  99 100 150]
y0 5
y1 4
y2 5
y3 6
y4 9
y5 28
y6 49
y7 72
y8 84
y9 93
y10 116
